### ISSUE TITLE
Handling multiple devices

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/apu#1]
Is there a way to target a particular device, when multiple devices / emulators are connected? I don't see any flags on the readme or am I missing something?

```
Installing com.example.app...
gradlew: 158: gradlew: Syntax error: "(" unexpected
error: more than one device/emulator
```

**Comment by cesarferreira** [comment]
Hey @ragunathjawahar the new version has that feature, it'll detect multiple devices and ask which one do you want to deploy to.

do a `gem update dryrun`  and let me know if you have it working
